- import_playbook: setup.yaml
- import_playbook: webserver.yaml
- import_playbook: rust.yaml
- import_playbook: go.yaml
- import_playbook: eigenlayer-cli.yaml

- hosts: batcher
  become: true
  vars:
    service: "batcher"

  tasks:
    # Install required packages
    - name: Update apt and install required system packages
      apt:
        pkg:
          - pkg-config
          - libssl-dev
        state: latest
        update_cache: true

    # Create directories for each service
    - name: Create directories for each service if do not exist
      ansible.builtin.file:
        path: /home/{{ ansible_user }}/repos/{{ service }}
        state: directory
        mode: '0755'
      become_user: "{{ ansible_user }}"

    # Clone Aligned repository for the service
    - name: Clone Aligned repository
      ansible.builtin.git:
        repo: https://github.com/yetanotherco/aligned_layer.git
        dest: /home/{{ ansible_user }}/repos/{{ service }}/aligned_layer
        version: batcher_ansible
      become_user: "{{ ansible_user }}"

    # Build the batcher
    - name: Build Batcher
      shell: cd /home/{{ ansible_user }}/repos/{{ service }}/aligned_layer && make deps && make install_batcher
      become_user: "{{ ansible_user }}"
      environment:
        PATH: "$PATH:/home/admin/.cargo/bin:/usr/local/go/bin:$GOPATH/bin:/$HOME/go/bin:/usr/bin"

    # Copy systemd service to user services
