- name: Eigenlayer CLI Setup
  hosts: all
  become: true

  tasks:
    - name: check if eigenlayer is installed
      become_user: "{{ app_user }}"
      shell: . ~/.profile && eigenlayer -v
      register: eigenlayer_exists
      ignore_errors: true

    - name: Download Eigenlayer CLI
      when: eigenlayer_exists is failed
      become_user: "{{ app_user }}"
      shell:
        cmd: curl -sSfL https://raw.githubusercontent.com/layr-labs/eigenlayer-cli/master/scripts/install.sh  | sh -s

    - name: Add eigenlayer path to ~/.profile
      when: eigenlayer_exists is failed
      become_user: "{{ app_user }}"
      lineinfile:
        path: ~/.profile
        line: 'export PATH=$PATH:~/bin'
        state: present

    - name: Source updated profile and test eigenlayer version
      when: eigenlayer_exists is failed
      become_user: "{{ app_user }}"
      shell: . ~/.profile && eigenlayer -v
