- name: Rust Setup
  hosts: all

  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      become: true
      changed_when: false

  tasks:
    - name: check if cargo is installed
      become_user: '{{ app_user }}'
      shell: /home/{{ app_user }}/.cargo/bin/cargo -v
      register: cargo_exists
      ignore_errors: true

    - name: Download Installer
      when: cargo_exists is failed
      become_user: '{{ app_user }}'
      get_url:
        url: https://sh.rustup.rs
        dest: /tmp/sh.rustup.rs
        mode: '0755'
        force: 'yes'
      tags:
        - rust

    - name: install rust/cargo
      when: cargo_exists is failed
      become_user: "{{ app_user }}"
      shell: /tmp/sh.rustup.rs -y && rm /tmp/sh.rustup.rs
      tags:
        - rust
