# Common variables for all the services
# 'production' only prints info and above. 'development' also prints debug
environment: 'development'
aligned_layer_deployment_config_file_path: './contracts/script/output/devnet/alignedlayer_deployment_output.json'
eigen_layer_deployment_config_file_path: './contracts/script/output/devnet/eigenlayer_deployment_output.json'
eth_rpc_url: 'http://localhost:8545'
eth_rpc_url_fallback: 'http://localhost:8545'
eth_ws_url: 'ws://localhost:8545'
eth_ws_url_fallback: 'ws://localhost:8545'
eigen_metrics_ip_port_address: 'localhost:9090'

## ECDSA Configurations
ecdsa:
  private_key_store_path: 'config-files/devnet/keys/operator-1.ecdsa.key.json'
  private_key_store_password: ''

## BLS Configurations
bls:
  private_key_store_path: 'config-files/devnet/keys/operator-1.bls.key.json'
  private_key_store_password: ''

## Operator Configurations
operator:
  aggregator_rpc_server_ip_port_address: localhost:8090
  operator_tracker_ip_port_address: http://localhost:4001
  address: 0x70997970C51812dc3A010C7d01b50e0d17dc79C8
  earnings_receiver_address: 0x70997970C51812dc3A010C7d01b50e0d17dc79C8
  delegation_approver_address: '0x0000000000000000000000000000000000000000'
  staker_opt_out_window_blocks: 0
  metadata_url: 'https://yetanotherco.github.io/operator_metadata/metadata.json'
  enable_metrics: true
  metrics_ip_port_address: localhost:9092
  max_batch_size: 268435456 # 256 MiB
  last_processed_batch_filepath: 'config-files/operator-1.last_processed_batch.json'

# Operators variables needed for register it in EigenLayer
el_delegation_manager_address: '0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9'
private_key_store_path: config-files/devnet/keys/operator-1.ecdsa.key.json
bls_private_key_store_path: config-files/devnet/keys/operator-1.bls.key.json
signer_type: local_keystore
chain_id: 31337
