{
 "title": "System Data",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 15, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style=\"background-color: #00A86B; color: white; padding: 10px; border-radius: 0px; text-align: center;\">\n  ETHEREUM\n</h1>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "options": {
    "content": "<h1 style=\"background-color: #00A86B; color: white; padding: 10px; border-radius: 0px; text-align: center;\">\n  HISTORIC DATA\n</h1>"
   }
  },
  {
   "title": "Ethereum Gas Price [GWEI]",
   "type": "stat",
   "description": "Ethereum Gas Price in GWEI",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "GWEI" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gas_price{job=\"aligned-tracker\"} * 10^-9",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ethereum Gas Price [GWEI]",
   "type": "timeseries",
   "description": "Ethereum Gas Price evolution in GWEI",
   "gridPos": { "h": 6, "w": 11, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "GWEI" } },
   "targets": [
    {
     "expr": "round(gas_price{job=\"aligned-tracker\"} * 10^-9 != 0, 0.00001)",
     "legendFormat": "."
    }
   ]
  },
  {
   "title": "Total Proofs Received",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(increase(received_proofs_count{job=\"aligned-batcher\"}[10y]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Batches Sent",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(increase(sent_batches_count{job=\"aligned-batcher\"}[10y]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gas Price on Latest Batch Sent [GWEI]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "GWEI" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gas_price_used_on_latest_batch{job=\"aligned-batcher\"} * 10^-9",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gas Price on Latest Batch Sent [GWEI]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "GWEI" } },
   "targets": [
    {
     "expr": "round(gas_price_used_on_latest_batch{job=\"aligned-batcher\"} * 10^-9 != 0, 0.00001)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total Tasks Received",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(increase(aligned_aggregator_received_tasks_count{bot=\"aggregator\"}[10y]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Tasks Verified",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(increase(aligned_aggregated_responses_count{bot=\"aggregator\"}[10y]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Accumulated Aggregator Extra Cost Paid [ETH]",
   "type": "stat",
   "description": "Accumulated gas cost the aggregator paid for the batcher when the tx cost was higher than the respondToTaskFeeLimit.",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(aligned_aggregator_gas_cost_paid_for_batcher_sum{bot=\"aggregator\"}[10y])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Accumulated Aggregator Gas Cost Paid [ETH]",
   "type": "stat",
   "description": "Accumulated gas cost in ETH the Aggregator paid when sending RespondToTask transactions.",
   "gridPos": { "h": 3, "w": 7, "x": 7, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(aligned_aggregator_gas_cost_paid_total_count{bot=\"aggregator\"}[10y])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# Times Aggregator Paid Extra Cost",
   "type": "stat",
   "description": "Number of times the aggregator paid for the batcher when the tx cost was higher than the respondToTaskFeeLimit",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(increase(aligned_aggregator_num_times_paid_for_batcher_count{bot=\"aggregator\"}[10y]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 20 },
   "options": {
    "content": "<h1 style=\"background-color: #00A86B; color: white; padding: 10px; border-radius: 0px; text-align: center;\">\n  SYSTEM STATUS\n</h1>"
   }
  },
  {
   "title": "Batcher Open Connections",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "open_connections_count{job=\"aligned-batcher\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tasks Not Verified",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A - $B", "reducer": "last", "type": "math" }
   ]
  },
  {
   "title": "Total Batcher Restarts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(increase(batcher_started_count{job=\"aligned-batcher\"}[10y]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Batcher Restarts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 7, "y": 27 },
   "targets": [
    {
     "expr": "floor(increase(batcher_started_count{job=\"aligned-batcher\"}[10y]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 33 },
   "options": {
    "content": "<h1 style=\"background-color: #00A86B; color: white; padding: 10px; border-radius: 0px; text-align: center;\">\n  BATCHER\n</h1>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 33 },
   "options": {
    "content": "<h1 style=\"background-color: #00A86B; color: white; padding: 10px; border-radius: 0px; text-align: center;\">\n  AGGREGATOR\n</h1>"
   }
  },
  {
   "title": "Batches Sent",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(increase(sent_batches_count{job=\"aligned-batcher\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Batches Sent",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 35 },
   "targets": [
    {
     "expr": "floor(increase(sent_batches_count{job=\"aligned-batcher\"}[10y]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tasks Received",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(increase(aligned_aggregator_received_tasks_count{bot=\"aggregator\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Verified Tasks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 35 },
   "targets": [
    {
     "expr": "floor(increase(aligned_aggregated_responses_count{bot=\"aggregator\"}[10y]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reverted Batches",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(increase(reverted_batches_count{job=\"aligned-batcher\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Batches Reverted",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 41 },
   "targets": [
    {
     "expr": "floor(increase(reverted_batches_count{job=\"aligned-batcher\"}[10y]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tasks Verified",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(increase(aligned_aggregated_responses_count{bot=\"aggregator\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Received Tasks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 41 },
   "targets": [
    {
     "expr": "floor(increase(aligned_aggregator_received_tasks_count{bot=\"aggregator\"}[10y]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Canceled Batches",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(increase(canceled_batches_count{job=\"aligned-batcher\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Batches Canceled",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 47 },
   "targets": [
    {
     "expr": "floor(increase(canceled_batches_count{job=\"aligned-batcher\"}[10y]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# Bumps Sending Responses to Ethereum",
   "type": "timeseries",
   "description": "Number of times gas price was bumped while sending an aggregated response.",
   "gridPos": { "h": 6, "w": 10, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "floor(increase(aligned_respond_to_task_gas_price_bumped_count{bot=\"aggregator\"}[10y]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queue Length",
   "type": "stat",
   "description": "Number of proofs in the queue",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "queue_len", "legendFormat": "Number of proofs in the queue" }
   ]
  },
  {
   "title": "Queue Length",
   "type": "timeseries",
   "description": "Number of proofs in the queue",
   "gridPos": { "h": 7, "w": 9, "x": 3, "y": 53 },
   "targets": [
    { "expr": "queue_len", "legendFormat": "Queue Length" }
   ]
  },
  {
   "title": "# Times Aggregator Paid Extra Cost",
   "type": "timeseries",
   "description": "Time series showing the number of times the aggregator paid for the batcher when the tx cost was higher than the respondToTaskFeeLimit",
   "gridPos": { "h": 7, "w": 10, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "floor(increase(aligned_aggregator_num_times_paid_for_batcher_count{bot=\"aggregator\"}[10y]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queue Size",
   "type": "stat",
   "description": "Sum of all proof sizes in the queue",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "queue_size_bytes", "legendFormat": "Size in bytes of the queue" }
   ]
  },
  {
   "title": "Queue Size",
   "type": "timeseries",
   "description": "Sum of all proof sizes in the queue",
   "gridPos": { "h": 7, "w": 9, "x": 3, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "queue_size_bytes", "legendFormat": "Queue Size" }
   ]
  },
  {
   "title": "Broken websocket connections",
   "type": "timeseries",
   "description": "Measures websocket connections that were abnormally disconnected.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "floor(increase(broken_ws_connections_count{job=\"aligned-batcher\"}[10y]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# User Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "floor(increase(user_errors_count{job=\"aligned-batcher\"}[10y]))",
     "legendFormat": "{{error_type}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 82 },
   "options": {
    "content": "<h1 style=\"background-color: #00A86B; color: white; padding: 10px; border-radius: 0px; text-align: center;\">\n  Latency\n</h1>"
   }
  },
  {
   "title": "Upload Batch to S3 Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "s3_duration * 10 ^ (-3)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Latest respond to task latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "aligned_aggregator_respond_to_task_latency{bot=\"aggregator\"}",
     "legendFormat": "Latest latency"
    }
   ]
  },
  {
   "title": "CreateNewTask Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "cancel_create_new_task_duration * 10 ^ (-3)",
     "legendFormat": "cancel_new_task"
    },
    {
     "expr": "create_new_task_duration * 10 ^(-3)",
     "legendFormat": "create_new_task"
    }
   ]
  },
  {
   "title": "Latest quorum reached latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "targets": [
    {
     "expr": "aligned_aggregator_task_quorum_reached_latency{bot=\"aggregator\"}",
     "legendFormat": "Latest latency"
    }
   ]
  }
 ]
}