- name: Elixir Setup
  hosts: "{{ host }}"

  vars:
    ansible_ssh_user: "{{ admin_user }}"

  tasks:
    # Install required packages
    - name: Update apt and install required system packages
      become: true
      ansible.builtin.apt:
        pkg:
          - build-essential
          - autoconf
          - m4
          - libncurses5-dev
          - libgl1-mesa-dev
          - libglu1-mesa-dev
          - libpng-dev
          - libssh-dev
          - unixodbc-dev
          - xsltproc
          - fop
          - libxml2-utils
          - libncurses-dev
        state: latest
        update_cache: true

    ########## Install libssl1.1 ##########
    - name: Check if libssl1.1 is installed
      become: true
      ansible.builtin.shell:
        cmd: dpkg -l | grep libssl1.1
      register: libssl_check
      changed_when: false
      failed_when: libssl_check.rc not in [0, 1]

    - name: Download libssl1.1
      become: true
      register: download_libssl
      ansible.builtin.get_url:
        url: http://ftp.de.debian.org/debian/pool/main/o/openssl/libssl1.1_1.1.1w-0+deb11u1_amd64.deb
        dest: /root/
      when: libssl_check.rc != 0

    - name: Install libssl1.1
      become: true
      ansible.builtin.apt:
        deb: "{{ download_libssl.dest }}"
      when: libssl_check.rc != 0

    - name: Check if Erlang 26.2.1-1 is installed
      become: true
      ansible.builtin.shell:
        cmd: dpkg -l | grep esl-erlang
      register: erlang_check
      changed_when: false
      failed_when: erlang_check.rc not in [0, 1]

    - name: Download Erlang 26.2.1-1
      become: true
      register: download_erlang
      ansible.builtin.get_url:
        url: https://binaries2.erlang-solutions.com/debian/pool/contrib/e/esl-erlang/esl-erlang_26.2.1-1~debian~bullseye_amd64.deb
        dest: /root/
      when: erlang_check.rc != 0

    - name: Install Erlang 26.2.1-1
      become: true
      ansible.builtin.apt:
        deb: "{{ download_erlang.dest }}"
      when: erlang_check.rc != 0

    ########## Install Elixir v1.16.2-otp-26 ##########
    - name: Check if Elixir v1.16.2 is installed
      become: true
      ansible.builtin.shell:
        cmd: elixir --version | grep "Elixir 1.16.2"
      register: elixir_check
      changed_when: false
      failed_when: elixir_check.rc not in [0, 1]

    - name: Download Elixir v1.16.2-otp-26
      become: true
      register: download_elixir
      ansible.builtin.get_url:
        url: https://github.com/elixir-lang/elixir/releases/download/v1.16.2/elixir-otp-26.zip
        dest: /root/
      when: elixir_check.rc != 0

    - name: Install Elixir v1.16.2-otp-26
      become: true
      ansible.builtin.unarchive:
        remote_src: true
        src: "{{ download_elixir.dest }}"
        dest: /usr/local/
      when: elixir_check.rc != 0
