name: build-go-projects

on:
  merge_group:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]
env:
  FFI_FOR_RELEASE: false
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: false
      - name: Build SP1 bindings
        run: make build_sp1_linux
      - name: Build Risc Zero go bindings
        run: make build_risc_zero_linux
      - name: Build Halo2-KZG bindings
        run: make build_halo2_kzg_linux
      - name: Build Halo2-IPA bindings
        run: make build_halo2_ipa_linux
      - name: Build Merkle Tree bindings
        run: make build_merkle_tree_linux
      - name: Build operator
        run: go build operator/cmd/main.go
      - name: Build aggregator
        run: go build aggregator/cmd/main.go
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
          override: true
      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            batcher/target
          key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-rust-
      - name: Check formatting of Rust projects
        run: |
          cd batcher
          cargo fmt --all -- --check
      - name: Run Clippy
        run: |
          cd batcher
          cargo clippy --all -- -D warnings
      - name: Build Rust projects
        run: |
          cd batcher
          cargo build --all
  
      
