name: Build contracts
on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]
    paths:
      - 'contracts/**'
      - 'foundry.toml'
      - '.github/workflows/build-contracts.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Build AlignedServiceManager
        run: make build_aligned_contracts
