name: Lint contracts
on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]
    paths:
      - "contracts/src/core/*.sol"
      - ".github/workflows/lint-contracts.yml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install
        working-directory: contracts

      - name: Run Solhint
        run: npm run lint:sol
        working-directory: contracts
