name: test-merkle-tree

on:
  merge_group:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]
    paths:
      - 'operator/merkle_tree/**'
      - '.github/workflows/test-merkle-tree.yml'

jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - name: Clear device space
          run: |
            sudo rm -rf "$AGENT_TOOLSDIRECTORY"
            sudo rm -rf /usr/local/lib/android
            sudo rm -rf /opt/ghc
            sudo rm -rf /usr/local/.ghcup
            sudo rm -rf /usr/share/dotnet
            sudo rm -rf /opt/ghc
            sudo rm -rf "/usr/local/share/boost"
        - uses: actions/checkout@v4
        - uses: actions/setup-go@v5
          with:
            go-version: '1.22'
            cache: false
        - uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
        - name: Test Merkle Tree Rust
          run: make test_merkle_tree_rust_ffi
        - name: Test Merkle Tree go bindings
          run: make test_merkle_tree_go_bindings_linux
