name: test-sp1

on:
  merge_group:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]
    paths:
      - 'operator/sp1/**'
      - '.github/workflows/test-sp1.yml'

jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-go@v5
          with:
            go-version: '1.22'
            cache: false
        - uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
        - name: Test SP1 Rust
          run: make test_sp1_rust_ffi
        - name: Test SP1 go bindings
          run: make test_sp1_go_bindings_linux
